name: Update license file

on:
  push:
    branches:
      - 'snyk-upgrade-*'

jobs:
  update_license_file:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install git secrets
        run: |
            wget --no-verbose -O git-secrets-1.3.0.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
            tar -zxf git-secrets-1.3.0.tar.gz
            cd git-secrets-1.3.0
            sudo make install   
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # Step that does that actual cache save and restore
      - uses: actions/cache@v3.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-maven-
      - name: Build with mvnw
        run: ./mvnw clean install

      - name: Push changes if license file changed
        run: |
          if [ -n "$(git status --porcelain | grep "THIRD-PARTY-LICENSES.txt")" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add THIRD-PARTY-LICENSES.txt
            git commit -m "Update license file"
            git push
          else
            echo "There were no changes to THIRD-PARTY-LICENSE.txt"
          fi
