extraction:
# Define settings for Java analysis
####################################
  java:
    before_index:
      # lgtm does a maven build so needs git-secrets
      - wget --no-verbose -O git-secrets-1.3.0.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
      - tar -zxf git-secrets-1.3.0.tar.gz
      - cd git-secrets-1.3.0
      - sudo make install
      - cd ../
    index:
    # Specify the Java version required to build the project.
      java_version: 12