---
swagger: "2.0"
info:
  description: "This describes the dockstore API, a webservice that manages pairs\
    \ of Docker images and associated metadata such as CWL documents and Dockerfiles\
    \ used to build those images. Explore swagger.json for a Swagger 2.0 description\
    \ of our API and explore openapi.yaml for OpenAPI 3.0 descriptions."
  version: "1.15.0-SNAPSHOT"
  title: "Dockstore API"
  termsOfService: "TBD"
  contact:
    name: "Dockstore@ga4gh"
    url: "https://discuss.dockstore.org/t/opening-helpdesk-tickets/1506"
    email: "theglobalalliance@genomicsandhealth.org"
  license:
    name: "Apache License Version 2.0"
    url: "https://github.com/dockstore/dockstore/blob/develop/LICENSE"
basePath: "/"
tags:
- name: "entries"
  description: "Interact with entries in Dockstore regardless of whether they are\
    \ containers or workflows"
- name: "containers"
  description: "List and register entries in the dockstore (pairs of images + metadata\
    \ (CWL and Dockerfile))"
- name: "aliases"
  description: "Create, update list aliases for accessing entries"
- name: "containertags"
  description: "List and modify tags for containers"
- name: "GA4GHV1"
  description: "A curated subset of resources proposed as a common standard for tool\
    \ repositories. Implements TRS [1.0.0](https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/1.0.0)\
    \ and is considered final (not subject to change)"
- name: "GA4GH"
  description: "A curated subset of resources proposed as a common standard for tool\
    \ repositories. Implements TRS [2.0.0-beta.2](https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/2.0.0-beta.2)\
    \ . Integrators are welcome to use these endpoints but they are subject to change\
    \ based on community input."
- name: "GA4GHV20"
  description: "A curated subset of resources proposed as a common standard for tool\
    \ repositories. Implements TRS [2.0.1](https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/2.0.1)."
- name: "extendedGA4GH"
  description: "Optional experimental extensions of the GA4GH API"
- name: "tokens"
  description: "List, modify, refresh, and delete tokens for external services"
- name: "workflows"
  description: "List and register workflows in the dockstore (CWL, Nextflow, WDL)"
- name: "organizations"
  description: "Operations on Dockstore organizations"
- name: "toolTester"
  description: "Interactions with the Dockstore-support's ToolTester application"
- name: "curation"
  description: "List and modify notifications for users of Dockstore"
- name: "NIHdatacommons"
  description: "Needed for SmartAPI compatibility apparantly, might be cargo cult\
    \ behaviour"
- name: "hosted"
  description: "Created and modify hosted entries in the dockstore"
- name: "users"
  description: "List, modify, and manage end users of the dockstore"
- name: "metadata"
  description: "Information about Dockstore like RSS, sitemap, lists of dependencies,\
    \ etc."
securityDefinitions:
  BEARER:
    type: "apiKey"
    name: "Authorization"
    in: "header"
externalDocs:
  description: "Dockstore documentation"
  url: "https://www.dockstore.org/docs/getting-started"
