name: Tagged release deploy

on:
  workflow_dispatch:
    inputs:
      changelist:
        description: 'patch and pre-release metadata'
        required: true
        default: '.0-alpha.1'


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-maven-
      - name: Deploy with mvnw
        run: |
         git config --global user.email "${{ github.actor }}"
         git config --global user.name "${{ github.actor }}"
         ./mvnw --batch-mode deploy -ntp -s .github/collab-mvn-settings.xml -DskipTests -Dchangelist=${{ github.event.inputs.changelist  }}
        env: 
          COLLAB_DEPLOY_TOKEN: ${{ secrets.COLLAB_DEPLOY_TOKEN }}
