name: Tagged release deploy

on:
  push:
    tags: [ '**' ]

jobs:
  deploy_artifacts:
    uses: dockstore/workflow-actions/.github/workflows/deploy_artifacts.yaml@seab-6771/reusable-image-deploy
    with:
      createDockerImage: true
      quayRepository: dockstore-webservice
    secrets: inherit
