name: Verify MacOS Installation Instructions

on:
  push:
    branches:
      - develop
      - feature/SEAB-4529/link-macos-instructions-to-github-action

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout dockstore/docktore
        uses: actions/checkout@v3
        with:
          repository: dockstore/dockstore
          path: dockstore
      - name: Checkout dockstore/docktore-ui2
        uses: actions/checkout@v3
        with:
          repository: dockstore/dockstore-ui2
          path: dockstore-ui2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install Brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        working-directory: dockstore
      - name: Run git
        run: git
        continue-on-error: true
        working-directory: dockstore
      - name: Setup git user information
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        working-directory: dockstore
      - name: Install Hubflow
        run: |
          git clone https://github.com/datasift/gitflow
          cd gitflow
          sudo ./install.sh
        working-directory: dockstore
      - name: Install JDK 17 # NOTE: this is not used, the java version installed at the beginning is used
        run: brew install openjdk@17
        working-directory: dockstore
      - name: Download and installl node.js
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        working-directory: dockstore
      - name: Install git secrets
        run: brew install git-secrets
        working-directory: dockstore
      - name: Install wget
        run: brew install wget
        working-directory: dockstore
      - name: Install jq
        run: brew install jq
        working-directory: dockstore
        
      - name: Build the webservice
        run: ./mvnw clean install
        working-directory: dockstore
        
      - name: Setup UI requirements
        run: npm ci --legacy-peer-deps
        working-directory: dockstore-ui2
      - name: Run prebuild
        run: npm run prebuild
        working-directory: dockstore-ui2
      - name: Run build
        run: npm run build
        working-directory: dockstore-ui2


      
