name: Verify MacOS Installation Instructions
# This job follows the instructions in README.md

on:
  schedule:
    - cron: '30 12 * * 1' #  This is every Monday at 5:30am PST/8:30am EST
    branches: develop

env:
  DOCKSTORE: dockstore
  DOCKSTORE_UI2: dockstore-ui2

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout dockstore/docktore
        uses: actions/checkout@v3
        with:
          repository: dockstore/dockstore
          path: ${{ env.DOCKSTORE }}
      - name: Checkout dockstore/docktore-ui2
        uses: actions/checkout@v3
        with:
          repository: dockstore/dockstore-ui2
          path: ${{ env.DOCKSTORE_UI2 }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install Brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        working-directory: ${{ env.DOCKSTORE }}
      - name: Run git
        run: git
        continue-on-error: true
        working-directory: ${{ env.DOCKSTORE }}
      - name: Setup git user information
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        working-directory: ${{ env.DOCKSTORE }}
      - name: Install Hubflow
        run: |
          git clone https://github.com/datasift/gitflow
          cd gitflow
          sudo ./install.sh
        working-directory: ${{ env.DOCKSTORE }}
      - name: Install JDK 17 # NOTE: this is not used, the java version installed at the beginning is used
        run: brew install openjdk@17
        working-directory: ${{ env.DOCKSTORE }}
      - name: Download and installl node.js
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        working-directory: ${{ env.DOCKSTORE }}
      - name: Install git secrets
        run: brew install git-secrets
        working-directory: ${{ env.DOCKSTORE }}
      - name: Install wget
        run: brew install wget
        working-directory: ${{ env.DOCKSTORE }}
      - name: Install jq
        run: brew install jq
        working-directory: ${{ env.DOCKSTORE }}
        
      - name: Build the webservice
        run: ./mvnw clean install
        working-directory: ${{ env.DOCKSTORE }}
        
      - name: Setup UI requirements
        run: npm ci --legacy-peer-deps
        working-directory: ${{ env.DOCKSTORE_UI2 }}
      - name: Run prebuild
        run: npm run prebuild
        working-directory: ${{ env.DOCKSTORE_UI2 }}
      - name: Run build
        run: npm run build
        working-directory: ${{ env.DOCKSTORE_UI2 }}
