# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]
jobs:
  javaTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
        chmod a+x yq_linux_amd64
        sudo mv yq_linux_amd64 /usr/bin/yq
    - name: Build SNAPSHOT of web service
      run: mvn -B clean install -DskipTests
    - name: Test with Maven
      working-directory: ./wdl-parsing/WDLParsingFunction
      run: mvn -B clean install
  testWithSAMCLI:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v1
       with:
         java-version: 11
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install aws-sam-cli
    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
        chmod a+x yq_linux_amd64
        sudo mv yq_linux_amd64 /usr/bin/yq
     - name: Build SNAPSHOT of web service
       working-directory: .
       run: mvn -B clean install -DskipTests
     - name: Build with SAM CLI
       working-directory: ./wdl-parsing
       run:  sam build
     - name: Test with SAM CLI
       working-directory: ./wdl-parsing
       run:  sam local invoke -e events/event.json   


