name: Validate openapi.yaml

on: [push]


jobs:
  test_swagger_editor_validator_remote:
    if: "!contains(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote


    steps:
      - uses: actions/checkout@v4
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.2
        with:
          definition-file: dockstore-webservice/src/main/resources/openapi3/openapi.yaml
